import 'cypress-xpath';
describe('Validação de Pedido - Tenda', () => {
    describe('Dado que desejo efetuar uma compra no site Tenda', () => {
        context('Quando adiciono diferentes produtos no carrinho', () => {
            it('Então produtos são apresentados no carrinho corretamente', () => {
                cy.login()
                cy.wait(3000)
                cy.get('li').contains('a', 'Marca própria').click({ force: true })
                cy.get('[id="buttonbuy-sku-"]').eq(0).click({ force: true })
                cy.wait(2000)
                cy.contains('a', 'Marketplace').click({ force: true })
                cy.wait(1000)
                cy.get('.title-subcategory').click({ force: true })
                cy.get('[id="buttonbuy-sku-"]').eq(0).click()
                cy.wait(1000)
                cy.get('.ItemListComponent').should('have.length', 2).and('be.visible')
                cy.wait(500)
                cy.get('span[itemprop="name"]').contains('Home').click();
                cy.wait(1000)
                cy.xpath(`(//span[@class='btn-action'][normalize-space()='+'])[1]`).click()
                cy.wait(3000)
                cy.xpath(`(//span[@class='btn-action'][normalize-space()='+'])[2]`).click()
                cy.wait(3000)
                cy.xpath(`(//span[@class='btn-action-decrement'][normalize-space()='_'])[1]`).click({ force: true })
                cy.wait(3000)
                cy.xpath(`(//span[@class='btn-action-decrement'][normalize-space()='_'])[1]`).click({ force: true })
                cy.wait(3000)
                cy.xpath(`(//span[@class='btn-action-decrement'][normalize-space()='_'])[1]`).click({ force: true })
                cy.wait(3000)
                cy.xpath(`(//span[@class='btn-action-decrement'][normalize-space()='_'])[1]`).click({ force: true })
                cy.wait(3000)
                cy.get('span.empty-cart').should('be.visible').and('have.text', 'Seu carrinho ainda está vazio.')
            })
        })
        context('Quando adiciono produto no carrinho', () => {
            context('E adiciono dados válidos de cartão de crédito', () => {
                it.only('Então pedido é concluído com sucesso', () => {
                    cy.login()
                    cy.wait(3000)
                    cy.contains('a', 'Marketplace').click({ force: true })
                    cy.wait(1000)
                    cy.get('.title-subcategory').click({ force: true })
                    cy.get('[id="buttonbuy-sku-"]').eq(0).click()
                    cy.wait(1000)
                    cy.get('button[data-cy="btn-"]').contains('Ver carrinho').click()
                    cy.get('a.btn.btn-finish-order').contains('Continuar').click()
                    cy.wait(1000)
                    cy.contains('button', 'Finalizar compra').click({ force: true })
                    cy.wait(3000)
                    cy.contains('button', 'Escolher endereço de entrega').click({ force: true });
                    cy.wait(2000)
                    cy.get('div.card-information-component').contains('Rua do Teste').click()
                    cy.wait(1000)
                    cy.contains('button', 'Finalizar compra').click({ force: true })
                    cy.wait(3000)
                })
            })
        })
    })
})